package com.oppo.camera.aps.config;

public class CameraFunction {
    public static final String AIS_SNAPSHOT = "func_ais_snapshot";
    public static final String AI_ENHANCEMENT_VIDEO = "func_enhancement_video";
    public static final String ALLMIGHTY_VIDEO = "func_allmighty_video";
    public static final String APS_BRACKETMODE = "func_aps_bracketmode";
    public static final String BOKEH = "func_bokeh";
    public static final String CACHE_CLICK_CAPTURE = "func_cache_click_capture";
    public static final String DERED_EYE = "func_dered_eye";
    public static final String DOUBLE_EXPOSURE = "func_video_double_exposure";
    public static final String FACE_BEAUTY_COMMON = "func_face_beauty_common";
    public static final String FACE_BEAUTY_CUSTOM = "func_face_beauty_custom";
    public static final int FACE_BEAUTY_FLAG = 0;
    public static final String FACE_BEAUTY_PROCESS = "func_face_beauty_process";
    public static final String FACE_BLUR = "func_face_blur";
    public static final String FACE_SLENDER_PROCESS = "func_face_slender_process";
    public static final int FILTER_FLAG = 1;
    public static final String FILTER_VIGNETTE = "func_filter_vignette";
    public static final String GOOGLE_LENS = "func_google_lens";
    public static final String ID_PHOTO = "func_id_photo";
    public static final String KEY_VIDEO_HYPER_LAPSE_PROCESS = "func_video_hyper_lapse_process";
    public static final String KEY_VIDEO_SUPER_EIS_PROCESS = "func_video_super_eis_process";
    public static final String KEY_VIDEO_SUPER_EIS_WIDE = "func_video_super_eis_wide";
    public static final int MASK_FLAG = 255;
    public static final String MODE_PANEL = "func_mode_panel";
    public static final String MOVIE_MODE_V2 = "func_movie_mode_v2";
    public static final String NEED_PREVIEW_STREAM = "need_preview_stream";
    public static final String RAW_HDR = "key_raw_hdr";
    public static final String REQUEST_FAST_LAUNCH = "func_request_fast_launch";
    public static final String RESET_AUTO_FOCUS = "func_reset_auto_focus";
    public static final String SAT_CAMERA = "func_sat_camera";
    public static final String SUPER_TEXT = "func_super_text";
    public static final String SUPER_TEXT_CPU_PROCESS = "func_super_text_cpu_process";
    public static final String SUPER_TEXT_GPU_PROCESS = "func_super_text_gpu_process";
    public static final String TILT_SHIFT = "func_tilt_shift";
    public static final String TORCH_SOFT_LIGHT = "func_torch_soft_light";
    public static final String ULTRA_NIGHT_VIDEO = "func_ultra_night_video";
    public static final String VIDEO_BLUR_PROCESS = "func_video_blur_process";
    public static final String VIDEO_HDR = "func_hdr";
    public static final String VIDEO_RETENTION = "func_video_retention";
}
