package com.oppo.camera.aps.constant;

import android.util.Size;
import com.oppo.camera.a.d;
import com.oppo.camera.a.e;
import com.oppo.camera.aps.adapter.ApsParameters;
import com.oppo.camera.statistics.CameraStatisticsUtil;
import com.oppo.camera.statistics.model.CaptureMsgData;
import java.util.Set;

public class ParameterKeys extends ApsParameters {
    public static final String ALGO_NAME_AIHDR = "aps_algo_aihdr";
    public static final String ALGO_NAME_AINR = "aps_algo_ainr";
    public static final String ALGO_NAME_AI_NIGHT = "aps_algo_ai_night";
    public static final String ALGO_NAME_BLURLESS = "aps_algo_blurless";
    public static final String ALGO_NAME_BOKEH = "aps_algo_bokeh";
    public static final String ALGO_NAME_COUPLE_HDR = "aps_algo_couple_hdr";
    public static final String ALGO_NAME_DARKSIGHT = "aps_algo_darksight";
    public static final String ALGO_NAME_DERED_EYE = "aps_algo_dered_eye";
    public static final String ALGO_NAME_FACE_BEAUTY = "aps_algo_face_beauty";
    public static final String ALGO_NAME_FACE_INFO = "aps_algo_face_info";
    public static final String ALGO_NAME_FACE_RECTIFY = "aps_algo_face_rectify";
    public static final String ALGO_NAME_FILTER = "aps_algo_filter";
    public static final String ALGO_NAME_FILTER_MICROSCOPE = "aps_algo_filter_microscope";
    public static final String ALGO_NAME_FRC = "preview_video_frc";
    public static final String ALGO_NAME_FRONT_BOKEH = "aps_algo_front_bokeh";
    public static final String ALGO_NAME_FRONT_PORTRAIT_SUPERNIGHT = "aps_algo_portrait_supernight";
    public static final String ALGO_NAME_FUSION = "aps_algo_fusion";
    public static final String ALGO_NAME_HDR = "aps_algo_hdr";
    public static final String ALGO_NAME_LOWLIGHT_HDR = "aps_algo_lowlight_hdr";
    public static final String ALGO_NAME_MFNR = "aps_algo_mfll";
    public static final String ALGO_NAME_MOTION_BLUR = "aps_algo_motion_blur";
    public static final String ALGO_NAME_NREE = "aps_algo_nree";
    public static final String ALGO_NAME_PF = "aps_algo_pf";
    public static final String ALGO_NAME_PF_V1 = "aps_algo_pf_v1";
    public static final String ALGO_NAME_PF_V3 = "aps_algo_pf_v3";
    public static final String ALGO_NAME_PIC_BEST = "aps_algo_pic_best";
    public static final String ALGO_NAME_RAW2YUV = "aps_algo_raw2yuv";
    public static final String ALGO_NAME_RAW_HDR = "aps_algo_raw_hdr";
    public static final String ALGO_NAME_RECTIFY = "aps_algo_rectify";
    public static final String ALGO_NAME_ROTATE_MIRROR = "aps_algo_rotate_mirror";
    public static final String ALGO_NAME_SCPORTRAIT = "aps_algo_scportrait";
    public static final String ALGO_NAME_SINGLE_AICOLOR = "aps_algo_single_aicolor";
    public static final String ALGO_NAME_SINGLE_BLUR = "aps_algo_single_blur";
    public static final String ALGO_NAME_SINGLE_BOKEH = "aps_algo_single_bokeh";
    public static final String ALGO_NAME_SUPERNIGHT = "aps_algo_supernight";
    public static final String ALGO_NAME_SUPERPHOTO = "aps_algo_superphoto";
    public static final String ALGO_NAME_SUPERSENSOR = "aps_algo_supersensor";
    public static final String ALGO_NAME_SUPER_TEXT = "aps_algo_super_text";
    public static final String ALGO_NAME_TILT_SHIFT = "aps_algo_tilt_shift";
    public static final String ALGO_NAME_UPSCALE = "aps_algo_upscale";
    public static final String ALGO_NAME_VIDEO_BLUR = "aps_algo_video_blur";
    public static final String ALGO_NAME_VIDEO_RETENTION = "aps_algo_video_retention";
    public static final String ALGO_NAME_WATERMARK = "aps_algo_watermark";
    public static final String APS_VIDEO_WATERMARK_NODE_NAME = "video_watermark";
    public static final ApsParameters.Key<String> KEY_10_BITS_ENABLE = new ApsParameters.Key<>("10bits_enable", 1, "0");
    public static final ApsParameters.Key<String> KEY_ACCELEROMETER_DATA = new ApsParameters.Key<>("accelerometer_data", 1);
    public static final ApsParameters.Key<String> KEY_ACCELEROMETER_USE = new ApsParameters.Key<>("accelerometer_use", 1);
    public static final ApsParameters.Key<String> KEY_AICOLOR_ENABLE = new ApsParameters.Key<>("aicolor_enable", 1);
    public static final ApsParameters.Key<String> KEY_AI_SCENE = new ApsParameters.Key<>("ai_scene", 1);
    public static final ApsParameters.Key<Boolean> KEY_AI_SHUTTER = new ApsParameters.Key<>("is_ai_shutter", 1, false);
    public static final ApsParameters.Key<String> KEY_BLUR_VALUE = new ApsParameters.Key<>("blur_value", 1);
    public static final ApsParameters.Key<String> KEY_CAMERA_FEATURE = new ApsParameters.Key<>("camera_feature", 1);
    public static final ApsParameters.Key<String> KEY_CAMERA_ID = new ApsParameters.Key<>(CameraStatisticsUtil.CAMERA_ID, 1);
    public static final ApsParameters.Key<String[]> KEY_CAPTURE_ALGO_LIST = new ApsParameters.Key<>("capture_algo_list", 1);
    public static final ApsParameters.Key<Integer> KEY_CAPTURE_FEATURE_TYPE = new ApsParameters.Key<>("capture_feature_type", 1);
    public static final ApsParameters.Key<Integer> KEY_CAPTURE_FRAME_COUNT = new ApsParameters.Key<>("capture_frame_count", 1);
    public static final ApsParameters.Key<Integer> KEY_CAPTURE_MFNR_NUM = new ApsParameters.Key<>("capture_mfnr_num", 1);
    public static final ApsParameters.Key<CaptureMsgData> KEY_CAPTURE_MSG_DATA = new ApsParameters.Key<>("capture_msgData", 2);
    public static final ApsParameters.Key<Integer> KEY_CAPTURE_REQUEST = new ApsParameters.Key<>("capture_request", 1);
    public static final ApsParameters.Key<Integer> KEY_CAPTURE_SCENE = new ApsParameters.Key<>("capture_scene", 1);
    public static final ApsParameters.Key<String> KEY_CROP_HEIGHT = new ApsParameters.Key<>("crop_height", 1, "0");
    public static final ApsParameters.Key<String> KEY_CROP_WIDTH = new ApsParameters.Key<>("crop_width", 1, "0");
    public static final ApsParameters.Key<int[]> KEY_CUSTOM_BEAUTY_PARAM = new ApsParameters.Key<>("custom_beauty_param", 2);
    public static final ApsParameters.Key<String> KEY_DCIP3_ENABLE = new ApsParameters.Key<>("dcip3_enable", 1);
    public static final ApsParameters.Key<String> KEY_DISPLAY_METRICS_HEIGHT = new ApsParameters.Key<>("display_metrics_height", 1);
    public static final ApsParameters.Key<String> KEY_DISPLAY_METRICS_WIDTH = new ApsParameters.Key<>("display_metrics_width", 1);
    public static final ApsParameters.Key<String> KEY_FACE_BEAUTY_VERSION = new ApsParameters.Key<>("face_beauty_version", 1);
    public static final ApsParameters.Key<Boolean> KEY_FAST_CAPTURE = new ApsParameters.Key<>("fast_capture", 2, true);
    public static final ApsParameters.Key<String> KEY_FILTER_TYPE = new ApsParameters.Key<>(CameraStatisticsUtil.FILTER_TYPE, 1);
    public static final ApsParameters.Key<String> KEY_FILTER_WITHVIGNETTE = new ApsParameters.Key<>("filter_withvignette", 1);
    public static final ApsParameters.Key<String> KEY_FLASH_STATUS = new ApsParameters.Key<>("flash_status", 1);
    public static final ApsParameters.Key<Integer> KEY_FRAME_FLAG = new ApsParameters.Key<>("frame_flag", 1, 0);
    public static final ApsParameters.Key<String> KEY_GPS_COORDS = new ApsParameters.Key<>("gps_coords", 1);
    public static final ApsParameters.Key<String> KEY_GPS_TIME = new ApsParameters.Key<>("gps_time", 1);
    public static final ApsParameters.Key<String> KEY_HEIF_ENABLE = new ApsParameters.Key<>("heif_enable", 1);
    public static final ApsParameters.Key<String> KEY_HIGHT_PICTURE_SIZE_ENABLE = new ApsParameters.Key<>("high_pic_size_enable", 1);
    public static final ApsParameters.Key<String> KEY_HYPER_LAPSE_RATE = new ApsParameters.Key<>("hyper_lapse_rate", 1);
    public static final ApsParameters.Key<Integer> KEY_HYPER_LAPSE_RECORDING_STATUS = new ApsParameters.Key<>("video_recording_status", 1);
    public static final ApsParameters.Key<Integer> KEY_IMAGE_HEIGHT = new ApsParameters.Key<>("image_height", 2, 0);
    public static final ApsParameters.Key<Integer> KEY_IMAGE_WIDTH = new ApsParameters.Key<>("image_width", 2, 0);
    public static final ApsParameters.Key<String> KEY_INPUT_EVLIST = new ApsParameters.Key<>("input_ev_list:", 1);
    public static final ApsParameters.Key<String> KEY_INTELLIGENT_CROP_REGION = new ApsParameters.Key<>("intelligent_crop_region", 1);
    public static final ApsParameters.Key<String> KEY_INTELLIGENT_FPS_RANGE = new ApsParameters.Key<>("intelligent_fps_range", 1, "0");
    public static final ApsParameters.Key<String> KEY_INTELLIGENT_OPENED = new ApsParameters.Key<>("intelligent_opened", 1, "0");
    public static final ApsParameters.Key<Boolean> KEY_IS_FROM_MAIN_MENU_APP = new ApsParameters.Key<>("is_from_main_menu_app", 1, true);
    public static final ApsParameters.Key<Boolean> KEY_IS_SUPER_TEXT_OPEN = new ApsParameters.Key<>("isSuperTextOpen", 2, false);
    public static final ApsParameters.Key<String> KEY_IS_VIDEO_3HDR_10BIT = new ApsParameters.Key<>("video_3hdr_10bit", 1, "0");
    public static final ApsParameters.Key<String> KEY_LENS_FACING = new ApsParameters.Key<>("lens_facing", 1);
    public static final ApsParameters.Key<Boolean> KEY_LSD_ENABLE = new ApsParameters.Key<>("lsd_enable", 1, false);
    public static final ApsParameters.Key<String> KEY_META_INDEX = new ApsParameters.Key<>("meta_index", 1);
    public static final ApsParameters.Key<Boolean> KEY_MIRROR_ENABLE = new ApsParameters.Key<>("mirror_enable", 2, false);
    public static final ApsParameters.Key<String> KEY_MONO_PORTRAIT = new ApsParameters.Key<>("mono_portrait", 1);
    public static final ApsParameters.Key<String> KEY_NEON_ENABLE = new ApsParameters.Key<>("neon_enable", 1);
    public static final ApsParameters.Key<String> KEY_OFFSET_DATE_TIME = new ApsParameters.Key<>("picture_offset_time", 1);
    public static final ApsParameters.Key<String> KEY_OPERATION_MODE = new ApsParameters.Key<>("operation_mode", 1);
    public static final ApsParameters.Key<Integer> KEY_ORIENTATION = new ApsParameters.Key<>(CameraStatisticsUtil.PORTRAIT_ORIENTATION, 2, 0);
    public static final ApsParameters.Key<Integer> KEY_OUTPUT_FORMAT = new ApsParameters.Key<>("output_format", 1, 0);
    public static final ApsParameters.Key<String> KEY_OUTPUT_HEIGHT = new ApsParameters.Key<>("output_height", 1);
    public static final ApsParameters.Key<int[]> KEY_OUTPUT_SIZE = new ApsParameters.Key<>("output_size", 2);
    public static final ApsParameters.Key<String> KEY_OUTPUT_WIDTH = new ApsParameters.Key<>("output_width", 1);
    public static final String KEY_PICTURE_DATE_TIME = "picture_date_time";
    public static final ApsParameters.Key<String> KEY_PICTURE_EXIF_FLAG = new ApsParameters.Key<>("picture_exif_flag", 2);
    public static final ApsParameters.Key<String> KEY_PICTURE_MIRROR = new ApsParameters.Key<>("mirror_enable", 1);
    public static final ApsParameters.Key<d> KEY_PICTURE_TAKEN_CALL_BACK = new ApsParameters.Key<>("pictureTakenCallback", 2);
    public static final ApsParameters.Key<String> KEY_PI_ENABLE = new ApsParameters.Key<>("pi_enable", 1);
    public static final ApsParameters.Key<String> KEY_PREVIEW_CALLBACK_TYPE = new ApsParameters.Key<>("preview_callback_type", 1);
    public static final String KEY_PREVIEW_CALLBACK_TYPE_DEFAULT = "0";
    public static final String KEY_PREVIEW_CALLBACK_TYPE_IMAGE = "1";
    public static final String KEY_PROCESS_IMAGE_TIME_FORMAT = "HHmmssSSS";
    public static final ApsParameters.Key<String> KEY_RETENTION_ENABLE = new ApsParameters.Key<>("retention_enable", 1);
    public static final ApsParameters.Key<String> KEY_RTB_ENABLE = new ApsParameters.Key<>("rtb_enable", 1);
    public static final ApsParameters.Key<Boolean> KEY_SLOW_VIDEO_HIGH_FRAME = new ApsParameters.Key<>("slowVideoHighFrame", 2, false);
    public static final ApsParameters.Key<String> KEY_SUPER_NIGHT_SCENE = new ApsParameters.Key<>("super_night_scene", 1);
    public static final ApsParameters.Key<String> KEY_SUPER_RAW_ENABLE = new ApsParameters.Key<>("super_raw_enable", 1);
    public static final ApsParameters.Key<String> KEY_SUPER_TEXT_ENABLE = new ApsParameters.Key<>("super_text_enable", 1);
    public static final ApsParameters.Key<e> KEY_SUPER_TEXT_RESULT_PROCESSOR = new ApsParameters.Key<>("superTextResultProcessor", 2);
    public static final ApsParameters.Key<String> KEY_SUPER_TEXT_VERTICES = new ApsParameters.Key<>("super_text_vertices", 1);
    public static final ApsParameters.Key<String> KEY_TILT_SHIFT = new ApsParameters.Key<>("tilt_shift", 1);
    public static final ApsParameters.Key<String> KEY_TILT_SHIFT_CENTER_POSITION = new ApsParameters.Key<>("tilt_shift_center_position", 1);
    public static final ApsParameters.Key<String> KEY_TILT_SHIFT_CLEAR_DISTANCE = new ApsParameters.Key<>("tilt_shift_clear_distance", 1);
    public static final ApsParameters.Key<String> KEY_TILT_SHIFT_PREVIEW_SIZE = new ApsParameters.Key<>("tilt_shift_preview_size", 1);
    public static final ApsParameters.Key<String> KEY_TILT_SHIFT_ROTATE_ANGLE = new ApsParameters.Key<>("tilt_shift_rotate_angle", 1);
    public static final ApsParameters.Key<String> KEY_TILT_SHIFT_TYPE = new ApsParameters.Key<>("tilt_shift_type", 1);
    public static final ApsParameters.Key<String> KEY_ULTRA_RESOLUTION = new ApsParameters.Key<>("ultra_resolution", 1);
    public static final ApsParameters.Key<Set<String>> KEY_UNINIT_ALGOS = new ApsParameters.Key<>("unInitAlgos", 2);
    public static final ApsParameters.Key<String> KEY_VIDEO_BLUR_EFFECT = new ApsParameters.Key<>("blur_status", 1);
    public static final ApsParameters.Key<String> KEY_VIDEO_BLUR_OPEN = new ApsParameters.Key<>("video_blur_open", 1);
    public static final ApsParameters.Key<String> KEY_VIDEO_BLUR_ORIENTATION = new ApsParameters.Key<>("video_blur_orientation", 1);
    public static final ApsParameters.Key<String> KEY_VIDEO_MIRROR = new ApsParameters.Key<>("video_is_mirrored", 1);
    public static final ApsParameters.Key<String> KEY_VIDEO_ORIENTATION = new ApsParameters.Key<>(CameraStatisticsUtil.VIDEO_ORIENTATION, 1);
    public static final ApsParameters.Key<String> KEY_VIDEO_RETENTION = new ApsParameters.Key<>("video_retention", 1);
    public static final ApsParameters.Key<String> KEY_VIDEO_RETENTION_ORIENTATION = new ApsParameters.Key<>("video_retention_orientation", 1);
    public static final ApsParameters.Key<Size> KEY_VIDEO_SIZE = new ApsParameters.Key<>("videoSize", 2);
    public static final ApsParameters.Key<String> KEY_VIDEO_WATERMARK_ENABLE = new ApsParameters.Key<>("video_watermark_enable", 1);
    public static final ApsParameters.Key<String> KEY_WATERMARK_PATH = new ApsParameters.Key<>("watermark_path", 2);
    public static final ApsParameters.Key<String> KEY_ZOOM_RATIO = new ApsParameters.Key<>("zoom_ratio", 1);
    public static final String PREVIEW_ALGO_NAME_ANTIBANDING = "preview_antibanding";
    public static final String PREVIEW_ALGO_NAME_ASD = "preview_asd";
    public static final String PREVIEW_ALGO_NAME_DEFAULT = "preview_default";
    public static final String PREVIEW_ALGO_NAME_FB = "preview_fb";
    public static final String PREVIEW_ALGO_NAME_PF_V3 = "preview_pf_v3";
    public static final String PREVIEW_ALGO_NAME_RECTIFY = "preview_rectify";
    public static final String PREVIEW_ALGO_NAME_RTB = "preview_rtb";
    public static final String PREVIEW_ALGO_NAME_VIDEO_FRC = "preview_video_frc";
    public static final String PREVIEW_ALGO_NAME_rectify = "preview_rectify";

    public static String getFlagState(boolean z) {
        return z ? "1" : "0";
    }
}
